import type { ResourceConfig } from "@/components/admin/resource-manager";

const L = (ar: string, en: string) => ({ ar, en });
const emptyL = { ar: "", en: "" };

export const sectorResource: ResourceConfig = {
  table: "sectors",
  singular: L("قطاع", "sector"),
  orderBy: "sort_order",
  reorderable: true,
  listColumns: [
    { key: "name", label: L("الاسم", "Name"), kind: "localized" },
    { key: "slug", label: L("المعرّف", "Slug") },
    { key: "icon", label: L("الأيقونة", "Icon") },
    { key: "published", label: L("الحالة", "Status"), kind: "boolean" },
  ],
  fields: [
    { key: "slug", label: L("المعرّف (slug)", "Slug"), type: "text" },
    { key: "name", label: L("الاسم", "Name"), type: "localized" },
    { key: "tagline", label: L("العنوان الفرعي", "Tagline"), type: "localized" },
    { key: "description", label: L("الوصف", "Description"), type: "localizedLong" },
    { key: "image", label: L("صورة الغلاف", "Cover image"), type: "image" },
    {
      key: "performance_summary",
      label: L("ملخص الأداء (ذكاء اصطناعي)", "Performance summary (AI)"),
      type: "localizedLong",
      help: L(
        "نص يلخّص أداء القطاع مؤخراً. يُملأ يدوياً حالياً، وسيُربط بتحديث تلقائي لاحقاً.",
        "A short recent-performance summary. Filled manually for now, will be automated later.",
      ),
    },
    {
      key: "icon",
      label: L("الأيقونة", "Icon"),
      type: "text",
      help: L("اسم أيقونة Lucide مثل Zap أو Rocket.", "A Lucide icon name, e.g. Zap or Rocket."),
    },
    { key: "tone", label: L("اللون", "Tone"), type: "text" },
    { key: "sort_order", label: L("الترتيب", "Order"), type: "number" },
    { key: "published", label: L("منشور", "Published"), type: "boolean" },
  ],
  defaults: () => ({
    slug: "",
    name: emptyL,
    tagline: emptyL,
    description: emptyL,
    image: "",
    performance_summary: emptyL,
    icon: "Sparkles",
    tone: "emerald",
    sort_order: 0,
    published: true,
  }),
};

export const companyResource: ResourceConfig = {
  table: "companies",
  singular: L("شركة", "company"),
  orderBy: "sort_order",
  listColumns: [
    { key: "name", label: L("الاسم", "Name"), kind: "localized" },
    { key: "ticker", label: L("الرمز", "Ticker") },
    { key: "exchange", label: L("السوق", "Exchange") },
    { key: "sector_id", label: L("القطاع", "Sector"), kind: "lookup", optionsKey: "sectors" },
    { key: "published", label: L("الحالة", "Status"), kind: "boolean" },
  ],
  fields: [
    { key: "slug", label: L("المعرّف (slug)", "Slug"), type: "text" },
    { key: "ticker", label: L("الرمز", "Ticker"), type: "text" },
    { key: "exchange", label: L("السوق", "Exchange"), type: "text" },
    { key: "sector_id", label: L("القطاع", "Sector"), type: "select", optionsKey: "sectors" },
    { key: "name", label: L("الاسم", "Name"), type: "localized" },
    { key: "logo", label: L("شعار الشركة", "Company logo"), type: "image" },
    { key: "country", label: L("الدولة", "Country"), type: "localized" },
    { key: "ceo", label: L("الرئيس التنفيذي", "CEO"), type: "localized" },
    { key: "founded_year", label: L("سنة التأسيس", "Founded year"), type: "number" },
    { key: "headquarters", label: L("المقر الرئيسي", "Headquarters"), type: "localized" },
    { key: "website", label: L("الموقع الإلكتروني", "Website"), type: "text" },
    { key: "price", label: L("السعر", "Price"), type: "text" },
    { key: "change", label: L("التغير", "Change"), type: "text" },
    { key: "market_cap", label: L("القيمة السوقية", "Market cap"), type: "text" },
    { key: "short", label: L("نبذة قصيرة", "Short summary"), type: "localized" },
    { key: "description", label: L("الوصف", "Description"), type: "localizedLong" },
    {
      key: "executive_summary",
      label: L("الملخص التنفيذي (نقاط القوة/المخاطر/المحفزات)", "Executive summary"),
      type: "json",
      help: L(
        '{"strengths":[{"ar":"","en":""}],"risks":[{"ar":"","en":""}],"catalysts":[{"ar":"","en":""}],"watchPoints":[{"ar":"","en":""}]}',
        '{"strengths":[{"ar":"","en":""}],"risks":[{"ar":"","en":""}],"catalysts":[{"ar":"","en":""}],"watchPoints":[{"ar":"","en":""}]}',
      ),
    },
    {
      key: "stock_performance",
      label: L("أداء السهم مقابل مؤشر", "Stock performance vs benchmark"),
      type: "json",
      help: L(
        '{"period":{"ar":"سنة","en":"1 year"},"companyReturn":12.8,"benchmarkName":{"ar":"تاسي","en":"TASI"},"benchmarkReturn":7.1}',
        '{"period":{"ar":"سنة","en":"1 year"},"companyReturn":12.8,"benchmarkName":{"ar":"تاسي","en":"TASI"},"benchmarkReturn":7.1}',
      ),
    },
    {
      key: "sections",
      label: L("أقسام التحليل", "Business sections"),
      type: "json",
      help: L(
        '[{"key":"model","title":{"ar":"","en":""},"body":{"ar":"","en":""}}]',
        '[{"key":"model","title":{"ar":"","en":""},"body":{"ar":"","en":""}}]',
      ),
    },
    {
      key: "financials",
      label: L("القوائم المالية", "Financials"),
      type: "json",
      help: L(
        '[{"year":"2024","revenue":"","netIncome":"","cashFlow":"","margin":"","roic":""}]',
        '[{"year":"2024","revenue":"","netIncome":"","cashFlow":"","margin":"","roic":""}]',
      ),
    },
    {
      key: "valuation",
      label: L("التقييم (شركة/قطاع/سوق)", "Valuation (company/sector/market)"),
      type: "json",
      help: L(
        '[{"label":{"ar":"P/E","en":"P/E"},"companyValue":"15.2x","sectorAvg":"17.8x","marketAvg":"21.4x","reading":"good","readingText":{"ar":"أقل من المتوسط","en":"Below average"}}]',
        '[{"label":{"ar":"P/E","en":"P/E"},"companyValue":"15.2x","sectorAvg":"17.8x","marketAvg":"21.4x","reading":"good","readingText":{"ar":"أقل من المتوسط","en":"Below average"}}]',
      ),
    },
    {
      key: "competitors",
      label: L("المنافسون", "Competitors"),
      type: "json",
      help: L(
        '[{"name":"Exxon Mobil","marketCap":"$470B","pe":"14.6x","dividend":"3.4%"}]',
        '[{"name":"Exxon Mobil","marketCap":"$470B","pe":"14.6x","dividend":"3.4%"}]',
      ),
    },
    {
      key: "financial_health",
      label: L("الصحة المالية", "Financial health"),
      type: "json",
      help: L(
        '[{"status":"good","text":{"ar":"سيولة قوية","en":"Strong liquidity"}}]',
        '[{"status":"good","text":{"ar":"سيولة قوية","en":"Strong liquidity"}}]',
      ),
    },
    {
      key: "growth_outlook",
      label: L("النمو المتوقع", "Growth outlook"),
      type: "json",
      help: L(
        '[{"label":{"ar":"نمو الإيرادات المتوقع","en":"Expected revenue growth"},"value":"+4.2%"}]',
        '[{"label":{"ar":"نمو الإيرادات المتوقع","en":"Expected revenue growth"},"value":"+4.2%"}]',
      ),
    },
    {
      key: "dividends",
      label: L("التوزيعات", "Dividends"),
      type: "json",
      help: L(
        '{"payer":true,"yield":"5.8%","lastPayout":"0.30","growth3y":"+6.2%","sustainabilityScore":78,"sustainabilityLabel":{"ar":"مرتفعة","en":"High"}}',
        '{"payer":true,"yield":"5.8%","lastPayout":"0.30","growth3y":"+6.2%","sustainabilityScore":78,"sustainabilityLabel":{"ar":"مرتفعة","en":"High"}}',
      ),
    },
    {
      key: "news",
      label: L("الأخبار", "News"),
      type: "json",
      help: L(
        '[{"title":{"ar":"","en":""},"source":"","date":"2026-01-01"}]',
        '[{"title":{"ar":"","en":""},"source":"","date":"2026-01-01"}]',
      ),
    },
    {
      key: "how_to_buy",
      label: L("كيف تشتري السهم", "How to buy"),
      type: "json",
      help: L('[{"ar":"","en":""}]', '[{"ar":"","en":""}]'),
    },
    {
      key: "financial_ratios",
      label: L("المؤشرات المالية (مجموعات)", "Financial ratios (grouped)"),
      type: "json",
      help: L(
        '[{"group":{"ar":"الربحية","en":"Profitability"},"rows":[{"label":{"ar":"ROE","en":"ROE"},"value":"26.4%","reading":"good"}]}]',
        '[{"group":{"ar":"الربحية","en":"Profitability"},"rows":[{"label":{"ar":"ROE","en":"ROE"},"value":"26.4%","reading":"good"}]}]',
      ),
    },
    {
      key: "balance_sheet",
      label: L("الميزانية العمومية", "Balance sheet"),
      type: "json",
      help: L(
        '[{"label":{"ar":"إجمالي الأصول","en":"Total assets"},"value":"660B$"}]',
        '[{"label":{"ar":"إجمالي الأصول","en":"Total assets"},"value":"660B$"}]',
      ),
    },
    {
      key: "short_interest",
      label: L("البيع على المكشوف", "Short interest"),
      type: "json",
      help: L(
        '{"percent":"1.2%","daysToCover":"2.1","note":{"ar":"","en":""}}',
        '{"percent":"1.2%","daysToCover":"2.1","note":{"ar":"","en":""}}',
      ),
    },
    {
      key: "trading_stats",
      label: L("إحصاءات التداول", "Trading stats"),
      type: "json",
      help: L(
        '{"weekLow52":"24.10","weekHigh52":"32.60","volume":"18.2M","beta":"0.85","creditRating":"A+"}',
        '{"weekLow52":"24.10","weekHigh52":"32.60","volume":"18.2M","beta":"0.85","creditRating":"A+"}',
      ),
    },
    {
      key: "ownership",
      label: L("الملكية والمساهمون", "Ownership"),
      type: "json",
      help: L(
        '{"government":"90.2%","freeFloat":"2.0%","holders":[{"name":{"ar":"صندوق الاستثمارات العامة","en":"PIF"},"percent":"16.0%"}]}',
        '{"government":"90.2%","freeFloat":"2.0%","holders":[{"name":{"ar":"","en":""},"percent":""}]}',
      ),
    },
    {
      key: "revenue_breakdown",
      label: L("تفصيل الإيرادات", "Revenue breakdown"),
      type: "json",
      help: L(
        '[{"label":{"ar":"الاستخراج","en":"Upstream"},"percent":58}]',
        '[{"label":{"ar":"الاستخراج","en":"Upstream"},"percent":58}]',
      ),
    },
    {
      key: "analyst_consensus",
      label: L("إجماع المحللين", "Analyst consensus"),
      type: "json",
      help: L(
        '{"rating":{"ar":"شراء","en":"Buy"},"analystCount":24,"targetPrice":"31.50","upside":"+13.1%"}',
        '{"rating":{"ar":"شراء","en":"Buy"},"analystCount":24,"targetPrice":"31.50","upside":"+13.1%"}',
      ),
    },
    {
      key: "upcoming_events",
      label: L("أحداث قادمة", "Upcoming events"),
      type: "json",
      help: L(
        '[{"title":{"ar":"إعلان النتائج","en":"Earnings"},"date":"2026-11-15","type":"earnings"}]',
        '[{"title":{"ar":"إعلان النتائج","en":"Earnings"},"date":"2026-11-15","type":"earnings"}]',
      ),
    },
    {
      key: "official_docs",
      label: L("مستندات رسمية", "Official documents"),
      type: "json",
      help: L(
        '[{"label":{"ar":"التقرير السنوي","en":"Annual report"},"url":"https://..."}]',
        '[{"label":{"ar":"التقرير السنوي","en":"Annual report"},"url":"https://..."}]',
      ),
    },
    {
      key: "data_sources",
      label: L("المصادر وحداثة البيانات", "Data sources"),
      type: "json",
      help: L(
        '[{"label":{"ar":"السعر","en":"Price"},"note":{"ar":"بيانات تجريبية","en":"Demo data"},"kind":"live"}]',
        '[{"label":{"ar":"السعر","en":"Price"},"note":{"ar":"","en":""},"kind":"live"}]',
      ),
    },
    { key: "sort_order", label: L("الترتيب", "Order"), type: "number" },
    { key: "published", label: L("منشور", "Published"), type: "boolean" },
  ],
  defaults: () => ({
    slug: "",
    ticker: "",
    exchange: "",
    sector_id: null,
    name: emptyL,
    logo: "",
    country: emptyL,
    ceo: emptyL,
    founded_year: null,
    headquarters: emptyL,
    website: "",
    price: "",
    change: "",
    market_cap: "",
    short: emptyL,
    description: emptyL,
    executive_summary: { strengths: [], risks: [], catalysts: [], watchPoints: [] },
    stock_performance: {
      period: emptyL,
      companyReturn: null,
      benchmarkName: emptyL,
      benchmarkReturn: null,
    },
    sections: [],
    financials: [],
    valuation: [],
    competitors: [],
    financial_health: [],
    growth_outlook: [],
    dividends: {
      payer: false,
      yield: "",
      lastPayout: "",
      growth3y: "",
      sustainabilityScore: null,
      sustainabilityLabel: emptyL,
    },
    news: [],
    how_to_buy: [],
    financial_ratios: [],
    balance_sheet: [],
    short_interest: { percent: "", daysToCover: "", note: emptyL },
    trading_stats: { weekLow52: "", weekHigh52: "", volume: "", beta: "", creditRating: "" },
    ownership: { government: "", freeFloat: "", holders: [] },
    revenue_breakdown: [],
    analyst_consensus: { rating: emptyL, analystCount: null, targetPrice: "", upside: "" },
    upcoming_events: [],
    official_docs: [],
    data_sources: [],
    sort_order: 0,
    published: true,
  }),
};

export const researchResource: ResourceConfig = {
  table: "research",
  singular: L("بحث", "research paper"),
  orderBy: "published_at",
  listColumns: [
    { key: "title", label: L("العنوان", "Title"), kind: "localized" },
    { key: "published_at", label: L("التاريخ", "Date") },
    { key: "sector_id", label: L("القطاع", "Sector"), kind: "lookup", optionsKey: "sectors" },
    { key: "published", label: L("الحالة", "Status"), kind: "boolean" },
  ],
  fields: [
    { key: "slug", label: L("المعرّف (slug)", "Slug"), type: "text" },
    { key: "title", label: L("العنوان", "Title"), type: "localized" },
    { key: "summary", label: L("الملخص", "Summary"), type: "localizedLong" },
    { key: "author", label: L("الكاتب", "Author"), type: "localized" },
    { key: "author_role", label: L("صفة الكاتب", "Author role"), type: "localized" },
    { key: "reading_time", label: L("وقت القراءة (دقائق)", "Reading time (min)"), type: "number" },
    { key: "published_at", label: L("تاريخ النشر", "Publish date"), type: "date" },
    { key: "image", label: L("صورة الغلاف", "Cover image URL"), type: "text" },
    { key: "sector_id", label: L("القطاع", "Sector"), type: "select", optionsKey: "sectors" },
    {
      key: "tags",
      label: L("الوسوم", "Tags"),
      type: "json",
      help: L('[{"ar":"","en":""}]', '[{"ar":"","en":""}]'),
    },
    {
      key: "sections",
      label: L("أقسام البحث", "Sections"),
      type: "json",
      help: L(
        '[{"id":"intro","heading":{"ar":"","en":""},"body":{"ar":"","en":""}}]',
        '[{"id":"intro","heading":{"ar":"","en":""},"body":{"ar":"","en":""}}]',
      ),
    },
    { key: "refs", label: L("المراجع", "References"), type: "json", help: L('["..."]', '["..."]') },
    { key: "published", label: L("منشور", "Published"), type: "boolean" },
  ],
  defaults: () => ({
    slug: "",
    title: emptyL,
    summary: emptyL,
    author: emptyL,
    author_role: emptyL,
    reading_time: 6,
    published_at: new Date().toISOString().slice(0, 10),
    image: "",
    sector_id: null,
    tags: [],
    sections: [],
    refs: [],
    published: true,
  }),
};

export const knowledgeResource: ResourceConfig = {
  table: "knowledge_articles",
  singular: L("مقال معرفي", "knowledge article"),
  orderBy: "sort_order",
  listColumns: [
    { key: "title", label: L("العنوان", "Title"), kind: "localized" },
    { key: "category", label: L("الفئة", "Category"), kind: "localized" },
    { key: "level", label: L("المستوى", "Level"), kind: "localized" },
    { key: "published", label: L("الحالة", "Status"), kind: "boolean" },
  ],
  fields: [
    { key: "slug", label: L("المعرّف (slug)", "Slug"), type: "text" },
    { key: "title", label: L("العنوان", "Title"), type: "localized" },
    { key: "summary", label: L("الملخص", "Summary"), type: "localizedLong" },
    { key: "category", label: L("الفئة", "Category"), type: "localized" },
    { key: "level", label: L("المستوى", "Level"), type: "localized" },
    { key: "icon", label: L("الأيقونة", "Icon"), type: "text" },
    { key: "reading_time", label: L("وقت القراءة (دقائق)", "Reading time (min)"), type: "number" },
    {
      key: "sections",
      label: L("أقسام الدرس", "Sections"),
      type: "json",
      help: L(
        '[{"heading":{"ar":"","en":""},"body":{"ar":"","en":""}}]',
        '[{"heading":{"ar":"","en":""},"body":{"ar":"","en":""}}]',
      ),
    },
    {
      key: "videos",
      label: L("الفيديوهات", "Videos"),
      type: "json",
      help: L(
        '[{"title":{"ar":"","en":""},"duration":"12:00","url":"https://youtube.com/watch?v=..."}]',
        '[{"title":{"ar":"","en":""},"duration":"12:00","url":"https://youtube.com/watch?v=..."}]',
      ),
    },
    { key: "sort_order", label: L("الترتيب", "Order"), type: "number" },
    { key: "published", label: L("منشور", "Published"), type: "boolean" },
  ],
  defaults: () => ({
    slug: "",
    title: emptyL,
    summary: emptyL,
    category: emptyL,
    level: emptyL,
    icon: "BookOpen",
    reading_time: 5,
    sections: [],
    videos: [],
    sort_order: 0,
    published: true,
  }),
};

export const boardResource: ResourceConfig = {
  table: "community_boards",
  singular: L("لوحة مجتمع", "community board"),
  orderBy: "sort_order",
  reorderable: true,
  listColumns: [
    { key: "name", label: L("الاسم", "Name"), kind: "localized" },
    { key: "slug", label: L("المعرّف", "Slug") },
    { key: "published", label: L("الحالة", "Status"), kind: "boolean" },
  ],
  fields: [
    { key: "slug", label: L("المعرّف (slug)", "Slug"), type: "text" },
    { key: "name", label: L("الاسم", "Name"), type: "localized" },
    { key: "description", label: L("الوصف", "Description"), type: "localizedLong" },
    { key: "image", label: L("صورة اللوحة", "Board image"), type: "image" },
    { key: "tone", label: L("اللون", "Tone"), type: "text" },
    { key: "sort_order", label: L("الترتيب", "Order"), type: "number" },
    { key: "published", label: L("منشورة", "Published"), type: "boolean" },
  ],
  defaults: () => ({
    slug: "",
    name: emptyL,
    description: emptyL,
    image: "",
    tone: "tone-emerald",
    sort_order: 0,
    published: true,
  }),
};

export const faqResource: ResourceConfig = {
  table: "faqs",
  singular: L("سؤال شائع", "FAQ"),
  orderBy: "sort_order",
  listColumns: [
    { key: "question", label: L("السؤال", "Question"), kind: "localized" },
    { key: "company_id", label: L("الشركة", "Company"), kind: "lookup", optionsKey: "companies" },
    { key: "published", label: L("الحالة", "Status"), kind: "boolean" },
  ],
  fields: [
    {
      key: "company_id",
      label: L("الشركة (اختياري)", "Company (optional)"),
      type: "select",
      optionsKey: "companies",
      help: L("اتركه فارغاً للأسئلة العامة.", "Leave empty for general FAQs."),
    },
    { key: "question", label: L("السؤال", "Question"), type: "localized" },
    { key: "answer", label: L("الإجابة", "Answer"), type: "localizedLong" },
    { key: "sort_order", label: L("الترتيب", "Order"), type: "number" },
    { key: "published", label: L("منشور", "Published"), type: "boolean" },
  ],
  defaults: () => ({
    company_id: null,
    question: emptyL,
    answer: emptyL,
    sort_order: 0,
    published: true,
  }),
};
