import type { ResourceConfig } from "@/components/admin/resource-manager";

const L = (ar: string, en: string) => ({ ar, en });
const emptyL = { ar: "", en: "" };

const readingOptions = [
  { value: "good", label: L("إيجابي", "Good") },
  { value: "warning", label: L("تحذير", "Warning") },
  { value: "bad", label: L("سلبي", "Bad") },
];

const statusOptions = [
  { value: "good", label: L("جيد ✓", "Good ✓") },
  { value: "warning", label: L("تحذير !", "Warning !") },
  { value: "bad", label: L("سلبي ✕", "Bad ✕") },
];

export const sectorResource: ResourceConfig = {
  table: "sectors",
  singular: L("قطاع", "sector"),
  orderBy: "sort_order",
  reorderable: true,
  listColumns: [
    { key: "name", label: L("الاسم", "Name"), kind: "localized" },
    { key: "slug", label: L("المعرّف", "Slug") },
    { key: "icon", label: L("الأيقونة", "Icon") },
    { key: "published", label: L("الحالة", "Status"), kind: "boolean" },
  ],
  fields: [
    { key: "slug", label: L("المعرّف (slug)", "Slug"), type: "text" },
    { key: "name", label: L("الاسم", "Name"), type: "localized" },
    { key: "tagline", label: L("العنوان الفرعي", "Tagline"), type: "localized" },
    { key: "description", label: L("الوصف", "Description"), type: "localizedLong" },
    { key: "image", label: L("صورة الغلاف", "Cover image"), type: "image" },
    {
      key: "performance_summary",
      label: L("ملخص الأداء (ذكاء اصطناعي)", "Performance summary (AI)"),
      type: "localizedLong",
      help: L(
        "نص يلخّص أداء القطاع مؤخراً. يُملأ يدوياً حالياً، وسيُربط بتحديث تلقائي لاحقاً.",
        "A short recent-performance summary. Filled manually for now, will be automated later.",
      ),
    },
    {
      key: "icon",
      label: L("الأيقونة", "Icon"),
      type: "text",
      help: L("اسم أيقونة Lucide مثل Zap أو Rocket.", "A Lucide icon name, e.g. Zap or Rocket."),
    },
    { key: "tone", label: L("اللون", "Tone"), type: "text" },
    { key: "sort_order", label: L("الترتيب", "Order"), type: "number" },
    { key: "published", label: L("منشور", "Published"), type: "boolean" },
  ],
  defaults: () => ({
    slug: "",
    name: emptyL,
    tagline: emptyL,
    description: emptyL,
    image: "",
    performance_summary: emptyL,
    icon: "Sparkles",
    tone: "emerald",
    sort_order: 0,
    published: true,
  }),
};

export const companyResource: ResourceConfig = {
  table: "companies",
  singular: L("شركة", "company"),
  orderBy: "sort_order",
  listColumns: [
    { key: "name", label: L("الاسم", "Name"), kind: "localized" },
    { key: "ticker", label: L("الرمز", "Ticker") },
    { key: "exchange", label: L("السوق", "Exchange") },
    { key: "sector_id", label: L("القطاع", "Sector"), kind: "lookup", optionsKey: "sectors" },
    { key: "published", label: L("الحالة", "Status"), kind: "boolean" },
  ],
  fields: [
    { key: "slug", label: L("المعرّف (slug)", "Slug"), type: "text" },
    { key: "ticker", label: L("الرمز", "Ticker"), type: "text" },
    { key: "exchange", label: L("السوق", "Exchange"), type: "text" },
    { key: "sector_id", label: L("القطاع", "Sector"), type: "select", optionsKey: "sectors" },
    { key: "name", label: L("الاسم", "Name"), type: "localized" },
    { key: "logo", label: L("شعار الشركة", "Company logo"), type: "image" },
    { key: "country", label: L("الدولة", "Country"), type: "localized" },
    { key: "ceo", label: L("الرئيس التنفيذي", "CEO"), type: "localized" },
    { key: "founded_year", label: L("سنة التأسيس", "Founded year"), type: "number" },
    { key: "headquarters", label: L("المقر الرئيسي", "Headquarters"), type: "localized" },
    { key: "website", label: L("الموقع الإلكتروني", "Website"), type: "text" },
    { key: "price", label: L("السعر", "Price"), type: "text" },
    { key: "change", label: L("التغير", "Change"), type: "text" },
    { key: "market_cap", label: L("القيمة السوقية", "Market cap"), type: "text" },
    { key: "short", label: L("نبذة قصيرة", "Short summary"), type: "localized" },
    { key: "description", label: L("الوصف", "Description"), type: "localizedLong" },
    {
      key: "executive_summary",
      label: L("الملخص التنفيذي (نقاط القوة/المخاطر/المحفزات)", "Executive summary"),
      type: "json",
      help: L(
        '{"strengths":[{"ar":"","en":""}],"risks":[{"ar":"","en":""}],"catalysts":[{"ar":"","en":""}],"watchPoints":[{"ar":"","en":""}]}',
        '{"strengths":[{"ar":"","en":""}],"risks":[{"ar":"","en":""}],"catalysts":[{"ar":"","en":""}],"watchPoints":[{"ar":"","en":""}]}',
      ),
    },
    {
      key: "stock_performance",
      label: L("أداء السهم مقابل مؤشر", "Stock performance vs benchmark"),
      type: "json",
      help: L(
        '{"period":{"ar":"سنة","en":"1 year"},"companyReturn":12.8,"benchmarkName":{"ar":"تاسي","en":"TASI"},"benchmarkReturn":7.1}',
        '{"period":{"ar":"سنة","en":"1 year"},"companyReturn":12.8,"benchmarkName":{"ar":"تاسي","en":"TASI"},"benchmarkReturn":7.1}',
      ),
    },
    {
      key: "sections",
      label: L("أقسام التحليل", "Business sections"),
      type: "list",
      itemColumns: [
        { key: "key", label: L("المعرّف", "Key"), placeholder: "model" },
        { key: "title", label: L("العنوان", "Title"), kind: "localized" },
        { key: "body", label: L("المحتوى", "Body"), kind: "localized" },
      ],
    },
    {
      key: "financials",
      label: L("القوائم المالية", "Financials"),
      type: "list",
      itemColumns: [
        { key: "year", label: L("السنة", "Year"), placeholder: "2024" },
        { key: "revenue", label: L("الإيرادات", "Revenue"), placeholder: "616.0B" },
        { key: "netIncome", label: L("صافي الدخل", "Net income"), placeholder: "126.2B" },
        { key: "cashFlow", label: L("التدفق النقدي", "Cash flow"), placeholder: "153.6B" },
        { key: "margin", label: L("الهامش", "Margin"), placeholder: "23.7%" },
        { key: "roic", label: L("العائد على رأس المال", "ROIC"), placeholder: "16.2%" },
      ],
    },
    {
      key: "valuation",
      label: L("التقييم (شركة/قطاع/سوق)", "Valuation (company/sector/market)"),
      type: "list",
      itemColumns: [
        { key: "label", label: L("المؤشر", "Metric"), kind: "localized" },
        { key: "companyValue", label: L("قيمة الشركة", "Company"), placeholder: "15.2x" },
        { key: "sectorAvg", label: L("متوسط القطاع", "Sector avg"), placeholder: "17.8x" },
        { key: "marketAvg", label: L("متوسط السوق", "Market avg"), placeholder: "21.4x" },
        {
          key: "reading",
          label: L("القراءة", "Reading"),
          kind: "select",
          options: [
            { value: "good", label: L("إيجابي", "Good") },
            { value: "warning", label: L("تحذير", "Warning") },
            { value: "bad", label: L("سلبي", "Bad") },
          ],
        },
        { key: "readingText", label: L("تفسير القراءة", "Reading text"), kind: "localized" },
      ],
    },
    {
      key: "competitors",
      label: L("المنافسون", "Competitors"),
      type: "list",
      itemColumns: [
        { key: "name", label: L("اسم الشركة", "Company name"), placeholder: "Exxon Mobil" },
        { key: "marketCap", label: L("القيمة السوقية", "Market cap"), placeholder: "$470B" },
        { key: "pe", label: L("مكرر الربحية", "P/E"), placeholder: "14.6x" },
        { key: "dividend", label: L("العائد", "Dividend"), placeholder: "3.4%" },
      ],
    },
    {
      key: "financial_health",
      label: L("الصحة المالية", "Financial health"),
      type: "list",
      itemColumns: [
        {
          key: "status",
          label: L("الحالة", "Status"),
          kind: "select",
          options: [
            { value: "good", label: L("جيد ✓", "Good ✓") },
            { value: "warning", label: L("تحذير !", "Warning !") },
            { value: "bad", label: L("سلبي ✕", "Bad ✕") },
          ],
        },
        { key: "text", label: L("الملاحظة", "Note"), kind: "localized" },
      ],
    },
    {
      key: "growth_outlook",
      label: L("النمو المتوقع", "Growth outlook"),
      type: "list",
      itemColumns: [
        { key: "label", label: L("البند", "Item"), kind: "localized" },
        { key: "value", label: L("القيمة", "Value"), placeholder: "+4.2%" },
      ],
    },
    {
      key: "dividends",
      label: L("التوزيعات", "Dividends"),
      type: "json",
      help: L(
        '{"payer":true,"yield":"5.8%","lastPayout":"0.30","growth3y":"+6.2%","sustainabilityScore":78,"sustainabilityLabel":{"ar":"مرتفعة","en":"High"}}',
        '{"payer":true,"yield":"5.8%","lastPayout":"0.30","growth3y":"+6.2%","sustainabilityScore":78,"sustainabilityLabel":{"ar":"مرتفعة","en":"High"}}',
      ),
    },
    {
      key: "news",
      label: L("الأخبار", "News"),
      type: "json",
      help: L(
        '[{"title":{"ar":"","en":""},"source":"","date":"2026-01-01"}]',
        '[{"title":{"ar":"","en":""},"source":"","date":"2026-01-01"}]',
      ),
    },
    {
      key: "how_to_buy",
      label: L("كيف تشتري السهم", "How to buy"),
      type: "json",
      help: L('[{"ar":"","en":""}]', '[{"ar":"","en":""}]'),
    },
    {
      key: "financial_ratios",
      label: L("المؤشرات المالية (مجموعات)", "Financial ratios (grouped)"),
      type: "json",
      help: L(
        '[{"group":{"ar":"الربحية","en":"Profitability"},"rows":[{"label":{"ar":"ROE","en":"ROE"},"value":"26.4%","reading":"good"}]}]',
        '[{"group":{"ar":"الربحية","en":"Profitability"},"rows":[{"label":{"ar":"ROE","en":"ROE"},"value":"26.4%","reading":"good"}]}]',
      ),
    },
    {
      key: "balance_sheet",
      label: L("الميزانية العمومية", "Balance sheet"),
      type: "list",
      itemColumns: [
        { key: "label", label: L("البند", "Item"), kind: "localized" },
        { key: "value", label: L("القيمة", "Value"), placeholder: "660B$" },
      ],
    },
    {
      key: "short_interest",
      label: L("البيع على المكشوف", "Short interest"),
      type: "json",
      help: L(
        '{"percent":"1.2%","daysToCover":"2.1","note":{"ar":"","en":""}}',
        '{"percent":"1.2%","daysToCover":"2.1","note":{"ar":"","en":""}}',
      ),
    },
    {
      key: "trading_stats",
      label: L("إحصاءات التداول", "Trading stats"),
      type: "json",
      help: L(
        '{"weekLow52":"24.10","weekHigh52":"32.60","volume":"18.2M","beta":"0.85","creditRating":"A+"}',
        '{"weekLow52":"24.10","weekHigh52":"32.60","volume":"18.2M","beta":"0.85","creditRating":"A+"}',
      ),
    },
    {
      key: "ownership",
      label: L("الملكية والمساهمون", "Ownership"),
      type: "json",
      help: L(
        '{"government":"90.2%","freeFloat":"2.0%","holders":[{"name":{"ar":"صندوق الاستثمارات العامة","en":"PIF"},"percent":"16.0%"}]}',
        '{"government":"90.2%","freeFloat":"2.0%","holders":[{"name":{"ar":"","en":""},"percent":""}]}',
      ),
    },
    {
      key: "revenue_breakdown",
      label: L("تفصيل الإيرادات", "Revenue breakdown"),
      type: "list",
      itemColumns: [
        { key: "label", label: L("النشاط", "Segment"), kind: "localized" },
        { key: "percent", label: L("النسبة %", "Percent %"), kind: "number", placeholder: "58" },
      ],
    },
    {
      key: "analyst_consensus",
      label: L("إجماع المحللين", "Analyst consensus"),
      type: "json",
      help: L(
        '{"rating":{"ar":"شراء","en":"Buy"},"analystCount":24,"targetPrice":"31.50","upside":"+13.1%"}',
        '{"rating":{"ar":"شراء","en":"Buy"},"analystCount":24,"targetPrice":"31.50","upside":"+13.1%"}',
      ),
    },
    {
      key: "upcoming_events",
      label: L("أحداث قادمة", "Upcoming events"),
      type: "list",
      itemColumns: [
        { key: "title", label: L("الحدث", "Event"), kind: "localized" },
        { key: "date", label: L("التاريخ", "Date"), placeholder: "2026-11-15" },
        {
          key: "type",
          label: L("النوع", "Type"),
          kind: "select",
          options: [
            { value: "earnings", label: L("نتائج مالية", "Earnings") },
            { value: "dividend", label: L("توزيعات", "Dividend") },
            { value: "other", label: L("أخرى", "Other") },
          ],
        },
      ],
    },
    {
      key: "official_docs",
      label: L("مستندات رسمية", "Official documents"),
      type: "list",
      itemColumns: [
        { key: "label", label: L("اسم المستند", "Document name"), kind: "localized" },
        { key: "url", label: L("الرابط", "URL"), placeholder: "https://..." },
      ],
    },
    {
      key: "data_sources",
      label: L("المصادر وحداثة البيانات", "Data sources"),
      type: "list",
      itemColumns: [
        { key: "label", label: L("نوع البيانات", "Data type"), kind: "localized" },
        { key: "note", label: L("الملاحظة", "Note"), kind: "localized" },
        {
          key: "kind",
          label: L("المصدر", "Source kind"),
          kind: "select",
          options: [
            { value: "live", label: L("مباشر", "Live") },
            { value: "official", label: L("رسمي", "Official") },
            { value: "ai", label: L("ذكاء اصطناعي", "AI") },
          ],
        },
      ],
    },
    { key: "employee_count", label: L("عدد الموظفين", "Employees"), type: "text" },
    {
      key: "insider_ownership",
      label: L("ملكية الإدارة بالأسهم", "Insider ownership"),
      type: "text",
    },
    {
      key: "decision_card",
      label: L("بطاقة القرار السريع", "Quick decision card"),
      type: "list",
      itemColumns: [
        { key: "label", label: L("البند", "Label"), kind: "localized" },
        { key: "value", label: L("القيمة", "Value"), kind: "localized" },
        { key: "reading", label: L("القراءة", "Reading"), kind: "select", options: readingOptions },
      ],
    },
    {
      key: "segment_profit",
      label: L("ربحية كل قطاع", "Profit by segment"),
      type: "list",
      itemColumns: [
        { key: "label", label: L("القطاع", "Segment"), kind: "localized" },
        { key: "revenueShare", label: L("من الإيراد", "of revenue"), placeholder: "58%" },
        { key: "profitShare", label: L("من الربح", "of profit"), placeholder: "74%" },
      ],
    },
    {
      key: "geographic_revenue",
      label: L("التوزيع الجغرافي للإيرادات", "Revenue by geography"),
      type: "list",
      itemColumns: [
        { key: "label", label: L("المنطقة", "Region"), kind: "localized" },
        { key: "percent", label: L("النسبة %", "Percent %"), kind: "number", placeholder: "62" },
      ],
    },
    {
      key: "customer_concentration",
      label: L("تركّز العملاء والموردين", "Customer concentration"),
      type: "list",
      itemColumns: [
        { key: "status", label: L("الحالة", "Status"), kind: "select", options: statusOptions },
        { key: "text", label: L("الملاحظة", "Note"), kind: "localized" },
      ],
    },
    {
      key: "operational_kpis",
      label: L("مؤشرات تشغيلية", "Operational KPIs"),
      type: "list",
      itemColumns: [
        { key: "label", label: L("المؤشر", "Metric"), kind: "localized" },
        { key: "value", label: L("القيمة", "Value"), placeholder: "~9M برميل" },
      ],
    },
    {
      key: "management_team",
      label: L("فريق الإدارة", "Management team"),
      type: "list",
      itemColumns: [
        { key: "role", label: L("المنصب", "Role"), kind: "localized" },
        { key: "name", label: L("الاسم", "Name"), kind: "localized" },
        { key: "tenure", label: L("المدة", "Tenure"), kind: "localized" },
      ],
    },
    {
      key: "current_projects",
      label: L("المشاريع الحالية", "Current projects"),
      type: "list",
      itemColumns: [
        { key: "title", label: L("المشروع", "Project"), kind: "localized" },
        { key: "status", label: L("الحالة", "Status"), kind: "localized" },
      ],
    },
    {
      key: "company_timeline",
      label: L("الجدول الزمني", "Timeline"),
      type: "list",
      itemColumns: [
        { key: "year", label: L("السنة", "Year"), placeholder: "1933" },
        { key: "event", label: L("الحدث", "Event"), kind: "localized" },
      ],
    },
    {
      key: "quarterly_results",
      label: L("الأداء الربعي", "Quarterly results"),
      type: "list",
      itemColumns: [
        { key: "quarter", label: L("الربع", "Quarter"), placeholder: "Q3 2026" },
        { key: "revenue", label: L("الإيراد", "Revenue"), placeholder: "158.2B" },
        { key: "profit", label: L("الربح", "Profit"), placeholder: "32.4B" },
        { key: "vsEstimate", label: L("مقابل التوقعات", "vs estimate"), kind: "localized" },
        { key: "reading", label: L("القراءة", "Reading"), kind: "select", options: readingOptions },
      ],
    },
    {
      key: "cash_flow",
      label: L("التدفقات النقدية", "Cash flow"),
      type: "list",
      itemColumns: [
        { key: "label", label: L("البند", "Item"), kind: "localized" },
        { key: "value", label: L("القيمة", "Value"), placeholder: "+198B$" },
        { key: "reading", label: L("القراءة", "Reading"), kind: "select", options: readingOptions },
      ],
    },
    {
      key: "share_count",
      label: L("عدد الأسهم والتخفيف", "Share count & dilution"),
      type: "json",
      help: L(
        '{"count":"242.0B","yearChange":"0.0%","buyback":{"ar":"","en":""}}',
        '{"count":"242.0B","yearChange":"0.0%","buyback":{"ar":"","en":""}}',
      ),
    },
    {
      key: "margin_trend",
      label: L("اتجاه الهوامش", "Margin trend"),
      type: "json",
      help: L(
        '{"note":{"ar":"","en":""},"values":[13.1,18.0,19.9,21.8,23.7]}',
        '{"note":{"ar":"","en":""},"values":[13.1,18.0,19.9,21.8,23.7]}',
      ),
    },
    {
      key: "debt_maturity",
      label: L("جدول استحقاق الديون", "Debt maturity"),
      type: "list",
      itemColumns: [
        { key: "year", label: L("السنة", "Year"), placeholder: "2027" },
        { key: "amount", label: L("المبلغ", "Amount"), placeholder: "4.2B$" },
      ],
    },
    {
      key: "capital_allocation",
      label: L("تخصيص رأس المال", "Capital allocation"),
      type: "list",
      itemColumns: [
        { key: "label", label: L("البند", "Item"), kind: "localized" },
        { key: "percent", label: L("النسبة %", "Percent %"), kind: "number", placeholder: "68" },
      ],
    },
    {
      key: "historical_valuation",
      label: L("التقييم التاريخي", "Historical valuation"),
      type: "list",
      itemColumns: [
        { key: "label", label: L("المؤشر", "Metric"), kind: "localized" },
        { key: "current", label: L("الحالي", "Current"), placeholder: "15.2x" },
        { key: "avg5y", label: L("متوسط 5 سنوات", "5y average"), placeholder: "18.4x" },
        { key: "reading", label: L("القراءة", "Reading"), kind: "select", options: readingOptions },
        { key: "readingText", label: L("تفسير القراءة", "Reading text"), kind: "localized" },
      ],
    },
    {
      key: "valuation_scenarios",
      label: L("سيناريوهات التقييم", "Valuation scenarios"),
      type: "json",
      help: L(
        '{"bear":{"price":"22.00","change":"-21%"},"base":{"price":"31.50","change":"+13%"},"bull":{"price":"38.00","change":"+36%"}}',
        '{"bear":{"price":"22.00","change":"-21%"},"base":{"price":"31.50","change":"+13%"},"bull":{"price":"38.00","change":"+36%"}}',
      ),
    },
    {
      key: "forward_estimates",
      label: L("التقديرات المستقبلية", "Forward estimates"),
      type: "list",
      itemColumns: [
        { key: "year", label: L("السنة", "Year"), placeholder: "2026e" },
        { key: "revenue", label: L("الإيراد المتوقع", "Revenue"), placeholder: "642B$" },
        { key: "forwardPe", label: L("P/E متوقع", "Forward P/E"), placeholder: "14.6x" },
      ],
    },
    {
      key: "insider_trades",
      label: L("تداولات الداخليين", "Insider trades"),
      type: "list",
      itemColumns: [
        { key: "text", label: L("الملاحظة", "Note"), kind: "localized" },
        {
          key: "direction",
          label: L("الاتجاه", "Direction"),
          kind: "select",
          options: [
            { value: "buy", label: L("شراء", "Buy") },
            { value: "sell", label: L("بيع", "Sell") },
            { value: "neutral", label: L("محايد", "Neutral") },
          ],
        },
      ],
    },
    {
      key: "risk_items",
      label: L("المخاطر المصنّفة", "Categorized risks"),
      type: "list",
      itemColumns: [
        { key: "category", label: L("التصنيف", "Category"), kind: "localized" },
        {
          key: "kind",
          label: L("النوع", "Kind"),
          kind: "select",
          options: [
            { value: "operational", label: L("تشغيلية", "Operational") },
            { value: "market", label: L("سوقية", "Market") },
            { value: "regulatory", label: L("تنظيمية", "Regulatory") },
            { value: "financial", label: L("مالية", "Financial") },
          ],
        },
        { key: "text", label: L("الوصف", "Description"), kind: "localized" },
      ],
    },
    {
      key: "regulatory_env",
      label: L("البيئة التنظيمية والكليات", "Regulatory & macro"),
      type: "list",
      itemColumns: [
        { key: "title", label: L("العامل", "Factor"), kind: "localized" },
        { key: "note", label: L("التأثير", "Impact"), kind: "localized" },
      ],
    },
    {
      key: "price_history",
      label: L("تاريخ سعر السهم (للشارت)", "Price history (chart)"),
      type: "list",
      itemColumns: [
        { key: "date", label: L("التاريخ", "Date"), placeholder: "2026-01" },
        { key: "price", label: L("السعر", "Price"), kind: "number", placeholder: "27.85" },
      ],
    },
    { key: "sort_order", label: L("الترتيب", "Order"), type: "number" },
    { key: "published", label: L("منشور", "Published"), type: "boolean" },
  ],
  defaults: () => ({
    slug: "",
    ticker: "",
    exchange: "",
    sector_id: null,
    name: emptyL,
    logo: "",
    country: emptyL,
    ceo: emptyL,
    founded_year: null,
    headquarters: emptyL,
    website: "",
    price: "",
    change: "",
    market_cap: "",
    short: emptyL,
    description: emptyL,
    executive_summary: { strengths: [], risks: [], catalysts: [], watchPoints: [] },
    stock_performance: {
      period: emptyL,
      companyReturn: null,
      benchmarkName: emptyL,
      benchmarkReturn: null,
    },
    sections: [],
    financials: [],
    valuation: [],
    competitors: [],
    financial_health: [],
    growth_outlook: [],
    dividends: {
      payer: false,
      yield: "",
      lastPayout: "",
      growth3y: "",
      sustainabilityScore: null,
      sustainabilityLabel: emptyL,
    },
    news: [],
    how_to_buy: [],
    employee_count: "",
    insider_ownership: "",
    decision_card: [],
    segment_profit: [],
    geographic_revenue: [],
    customer_concentration: [],
    operational_kpis: [],
    management_team: [],
    current_projects: [],
    company_timeline: [],
    quarterly_results: [],
    cash_flow: [],
    share_count: { count: "", yearChange: "", buyback: emptyL },
    margin_trend: { note: emptyL, values: [] },
    debt_maturity: [],
    capital_allocation: [],
    historical_valuation: [],
    valuation_scenarios: {
      bear: { price: "", change: "" },
      base: { price: "", change: "" },
      bull: { price: "", change: "" },
    },
    forward_estimates: [],
    insider_trades: [],
    risk_items: [],
    regulatory_env: [],
    price_history: [],
    financial_ratios: [],
    balance_sheet: [],
    short_interest: { percent: "", daysToCover: "", note: emptyL },
    trading_stats: { weekLow52: "", weekHigh52: "", volume: "", beta: "", creditRating: "" },
    ownership: { government: "", freeFloat: "", holders: [] },
    revenue_breakdown: [],
    analyst_consensus: { rating: emptyL, analystCount: null, targetPrice: "", upside: "" },
    upcoming_events: [],
    official_docs: [],
    data_sources: [],
    sort_order: 0,
    published: true,
  }),
};

export const researchResource: ResourceConfig = {
  table: "research",
  singular: L("بحث", "research paper"),
  orderBy: "published_at",
  listColumns: [
    { key: "title", label: L("العنوان", "Title"), kind: "localized" },
    { key: "published_at", label: L("التاريخ", "Date") },
    { key: "sector_id", label: L("القطاع", "Sector"), kind: "lookup", optionsKey: "sectors" },
    { key: "published", label: L("الحالة", "Status"), kind: "boolean" },
  ],
  fields: [
    { key: "slug", label: L("المعرّف (slug)", "Slug"), type: "text" },
    { key: "title", label: L("العنوان", "Title"), type: "localized" },
    { key: "summary", label: L("الملخص", "Summary"), type: "localizedLong" },
    { key: "author", label: L("الكاتب", "Author"), type: "localized" },
    { key: "author_role", label: L("صفة الكاتب", "Author role"), type: "localized" },
    { key: "reading_time", label: L("وقت القراءة (دقائق)", "Reading time (min)"), type: "number" },
    { key: "published_at", label: L("تاريخ النشر", "Publish date"), type: "date" },
    { key: "image", label: L("صورة الغلاف", "Cover image URL"), type: "text" },
    { key: "sector_id", label: L("القطاع", "Sector"), type: "select", optionsKey: "sectors" },
    {
      key: "tags",
      label: L("الوسوم", "Tags"),
      type: "json",
      help: L('[{"ar":"","en":""}]', '[{"ar":"","en":""}]'),
    },
    {
      key: "sections",
      label: L("أقسام البحث", "Sections"),
      type: "json",
      help: L(
        '[{"id":"intro","heading":{"ar":"","en":""},"body":{"ar":"","en":""}}]',
        '[{"id":"intro","heading":{"ar":"","en":""},"body":{"ar":"","en":""}}]',
      ),
    },
    { key: "refs", label: L("المراجع", "References"), type: "json", help: L('["..."]', '["..."]') },
    { key: "published", label: L("منشور", "Published"), type: "boolean" },
  ],
  defaults: () => ({
    slug: "",
    title: emptyL,
    summary: emptyL,
    author: emptyL,
    author_role: emptyL,
    reading_time: 6,
    published_at: new Date().toISOString().slice(0, 10),
    image: "",
    sector_id: null,
    tags: [],
    sections: [],
    refs: [],
    published: true,
  }),
};

export const knowledgeResource: ResourceConfig = {
  table: "knowledge_articles",
  singular: L("مقال معرفي", "knowledge article"),
  orderBy: "sort_order",
  listColumns: [
    { key: "title", label: L("العنوان", "Title"), kind: "localized" },
    { key: "category", label: L("الفئة", "Category"), kind: "localized" },
    { key: "level", label: L("المستوى", "Level"), kind: "localized" },
    { key: "published", label: L("الحالة", "Status"), kind: "boolean" },
  ],
  fields: [
    { key: "slug", label: L("المعرّف (slug)", "Slug"), type: "text" },
    { key: "title", label: L("العنوان", "Title"), type: "localized" },
    { key: "summary", label: L("الملخص", "Summary"), type: "localizedLong" },
    { key: "category", label: L("الفئة", "Category"), type: "localized" },
    { key: "level", label: L("المستوى", "Level"), type: "localized" },
    { key: "icon", label: L("الأيقونة", "Icon"), type: "text" },
    { key: "reading_time", label: L("وقت القراءة (دقائق)", "Reading time (min)"), type: "number" },
    {
      key: "sections",
      label: L("أقسام الدرس", "Sections"),
      type: "json",
      help: L(
        '[{"heading":{"ar":"","en":""},"body":{"ar":"","en":""}}]',
        '[{"heading":{"ar":"","en":""},"body":{"ar":"","en":""}}]',
      ),
    },
    {
      key: "videos",
      label: L("الفيديوهات", "Videos"),
      type: "json",
      help: L(
        '[{"title":{"ar":"","en":""},"duration":"12:00","url":"https://youtube.com/watch?v=..."}]',
        '[{"title":{"ar":"","en":""},"duration":"12:00","url":"https://youtube.com/watch?v=..."}]',
      ),
    },
    { key: "sort_order", label: L("الترتيب", "Order"), type: "number" },
    { key: "published", label: L("منشور", "Published"), type: "boolean" },
  ],
  defaults: () => ({
    slug: "",
    title: emptyL,
    summary: emptyL,
    category: emptyL,
    level: emptyL,
    icon: "BookOpen",
    reading_time: 5,
    sections: [],
    videos: [],
    sort_order: 0,
    published: true,
  }),
};

export const boardResource: ResourceConfig = {
  table: "community_boards",
  singular: L("لوحة مجتمع", "community board"),
  orderBy: "sort_order",
  reorderable: true,
  listColumns: [
    { key: "name", label: L("الاسم", "Name"), kind: "localized" },
    { key: "slug", label: L("المعرّف", "Slug") },
    { key: "published", label: L("الحالة", "Status"), kind: "boolean" },
  ],
  fields: [
    { key: "slug", label: L("المعرّف (slug)", "Slug"), type: "text" },
    { key: "name", label: L("الاسم", "Name"), type: "localized" },
    { key: "description", label: L("الوصف", "Description"), type: "localizedLong" },
    { key: "image", label: L("صورة اللوحة", "Board image"), type: "image" },
    { key: "tone", label: L("اللون", "Tone"), type: "text" },
    { key: "sort_order", label: L("الترتيب", "Order"), type: "number" },
    { key: "published", label: L("منشورة", "Published"), type: "boolean" },
  ],
  defaults: () => ({
    slug: "",
    name: emptyL,
    description: emptyL,
    image: "",
    tone: "tone-emerald",
    sort_order: 0,
    published: true,
  }),
};

export const faqResource: ResourceConfig = {
  table: "faqs",
  singular: L("سؤال شائع", "FAQ"),
  orderBy: "sort_order",
  listColumns: [
    { key: "question", label: L("السؤال", "Question"), kind: "localized" },
    { key: "company_id", label: L("الشركة", "Company"), kind: "lookup", optionsKey: "companies" },
    { key: "published", label: L("الحالة", "Status"), kind: "boolean" },
  ],
  fields: [
    {
      key: "company_id",
      label: L("الشركة (اختياري)", "Company (optional)"),
      type: "select",
      optionsKey: "companies",
      help: L("اتركه فارغاً للأسئلة العامة.", "Leave empty for general FAQs."),
    },
    { key: "question", label: L("السؤال", "Question"), type: "localized" },
    { key: "answer", label: L("الإجابة", "Answer"), type: "localizedLong" },
    { key: "sort_order", label: L("الترتيب", "Order"), type: "number" },
    { key: "published", label: L("منشور", "Published"), type: "boolean" },
  ],
  defaults: () => ({
    company_id: null,
    question: emptyL,
    answer: emptyL,
    sort_order: 0,
    published: true,
  }),
};
