import type { ResourceConfig } from "@/components/admin/resource-manager";

const L = (ar: string, en: string) => ({ ar, en });
const emptyL = { ar: "", en: "" };

export const sectorResource: ResourceConfig = {
  table: "sectors",
  singular: L("قطاع", "sector"),
  orderBy: "sort_order",
  reorderable: true,
  listColumns: [
    { key: "name", label: L("الاسم", "Name"), kind: "localized" },
    { key: "slug", label: L("المعرّف", "Slug") },
    { key: "icon", label: L("الأيقونة", "Icon") },
    { key: "published", label: L("الحالة", "Status"), kind: "boolean" },
  ],
  fields: [
    { key: "slug", label: L("المعرّف (slug)", "Slug"), type: "text" },
    { key: "name", label: L("الاسم", "Name"), type: "localized" },
    { key: "tagline", label: L("العنوان الفرعي", "Tagline"), type: "localized" },
    { key: "description", label: L("الوصف", "Description"), type: "localizedLong" },
    { key: "image", label: L("صورة الغلاف", "Cover image"), type: "image" },
    {
      key: "icon",
      label: L("الأيقونة", "Icon"),
      type: "text",
      help: L("اسم أيقونة Lucide مثل Zap أو Rocket.", "A Lucide icon name, e.g. Zap or Rocket."),
    },
    { key: "tone", label: L("اللون", "Tone"), type: "text" },
    { key: "sort_order", label: L("الترتيب", "Order"), type: "number" },
    { key: "published", label: L("منشور", "Published"), type: "boolean" },
  ],
  defaults: () => ({
    slug: "",
    name: emptyL,
    tagline: emptyL,
    description: emptyL,
    image: "",
    icon: "Sparkles",
    tone: "emerald",
    sort_order: 0,
    published: true,
  }),
};

export const companyResource: ResourceConfig = {
  table: "companies",
  singular: L("شركة", "company"),
  orderBy: "sort_order",
  listColumns: [
    { key: "name", label: L("الاسم", "Name"), kind: "localized" },
    { key: "ticker", label: L("الرمز", "Ticker") },
    { key: "exchange", label: L("السوق", "Exchange") },
    { key: "sector_id", label: L("القطاع", "Sector"), kind: "lookup", optionsKey: "sectors" },
    { key: "published", label: L("الحالة", "Status"), kind: "boolean" },
  ],
  fields: [
    { key: "slug", label: L("المعرّف (slug)", "Slug"), type: "text" },
    { key: "ticker", label: L("الرمز", "Ticker"), type: "text" },
    { key: "exchange", label: L("السوق", "Exchange"), type: "text" },
    { key: "sector_id", label: L("القطاع", "Sector"), type: "select", optionsKey: "sectors" },
    { key: "name", label: L("الاسم", "Name"), type: "localized" },
    { key: "logo", label: L("شعار الشركة", "Company logo"), type: "image" },
    { key: "country", label: L("الدولة", "Country"), type: "localized" },
    { key: "price", label: L("السعر", "Price"), type: "text" },
    { key: "change", label: L("التغير", "Change"), type: "text" },
    { key: "market_cap", label: L("القيمة السوقية", "Market cap"), type: "text" },
    { key: "short", label: L("نبذة قصيرة", "Short summary"), type: "localized" },
    { key: "description", label: L("الوصف", "Description"), type: "localizedLong" },
    {
      key: "sections",
      label: L("أقسام التحليل", "Business sections"),
      type: "json",
      help: L(
        '[{"key":"model","title":{"ar":"","en":""},"body":{"ar":"","en":""}}]',
        '[{"key":"model","title":{"ar":"","en":""},"body":{"ar":"","en":""}}]',
      ),
    },
    {
      key: "financials",
      label: L("القوائم المالية", "Financials"),
      type: "json",
      help: L(
        '[{"year":"2024","revenue":"","netIncome":"","cashFlow":"","margin":"","roic":""}]',
        '[{"year":"2024","revenue":"","netIncome":"","cashFlow":"","margin":"","roic":""}]',
      ),
    },
    {
      key: "valuation",
      label: L("مؤشرات التقييم", "Valuation metrics"),
      type: "json",
      help: L(
        '[{"label":{"ar":"","en":""},"value":""}]',
        '[{"label":{"ar":"","en":""},"value":""}]',
      ),
    },
    {
      key: "news",
      label: L("الأخبار", "News"),
      type: "json",
      help: L(
        '[{"title":{"ar":"","en":""},"source":"","date":"2026-01-01"}]',
        '[{"title":{"ar":"","en":""},"source":"","date":"2026-01-01"}]',
      ),
    },
    {
      key: "how_to_buy",
      label: L("كيف تشتري السهم", "How to buy"),
      type: "json",
      help: L('[{"ar":"","en":""}]', '[{"ar":"","en":""}]'),
    },
    { key: "sort_order", label: L("الترتيب", "Order"), type: "number" },
    { key: "published", label: L("منشور", "Published"), type: "boolean" },
  ],
  defaults: () => ({
    slug: "",
    ticker: "",
    exchange: "",
    sector_id: null,
    name: emptyL,
    logo: "",
    country: emptyL,
    price: "",
    change: "",
    market_cap: "",
    short: emptyL,
    description: emptyL,
    sections: [],
    financials: [],
    valuation: [],
    news: [],
    how_to_buy: [],
    sort_order: 0,
    published: true,
  }),
};

export const researchResource: ResourceConfig = {
  table: "research",
  singular: L("بحث", "research paper"),
  orderBy: "published_at",
  listColumns: [
    { key: "title", label: L("العنوان", "Title"), kind: "localized" },
    { key: "published_at", label: L("التاريخ", "Date") },
    { key: "sector_id", label: L("القطاع", "Sector"), kind: "lookup", optionsKey: "sectors" },
    { key: "published", label: L("الحالة", "Status"), kind: "boolean" },
  ],
  fields: [
    { key: "slug", label: L("المعرّف (slug)", "Slug"), type: "text" },
    { key: "title", label: L("العنوان", "Title"), type: "localized" },
    { key: "summary", label: L("الملخص", "Summary"), type: "localizedLong" },
    { key: "author", label: L("الكاتب", "Author"), type: "localized" },
    { key: "author_role", label: L("صفة الكاتب", "Author role"), type: "localized" },
    { key: "reading_time", label: L("وقت القراءة (دقائق)", "Reading time (min)"), type: "number" },
    { key: "published_at", label: L("تاريخ النشر", "Publish date"), type: "date" },
    { key: "image", label: L("صورة الغلاف", "Cover image URL"), type: "text" },
    { key: "sector_id", label: L("القطاع", "Sector"), type: "select", optionsKey: "sectors" },
    {
      key: "tags",
      label: L("الوسوم", "Tags"),
      type: "json",
      help: L('[{"ar":"","en":""}]', '[{"ar":"","en":""}]'),
    },
    {
      key: "sections",
      label: L("أقسام البحث", "Sections"),
      type: "json",
      help: L(
        '[{"id":"intro","heading":{"ar":"","en":""},"body":{"ar":"","en":""}}]',
        '[{"id":"intro","heading":{"ar":"","en":""},"body":{"ar":"","en":""}}]',
      ),
    },
    { key: "refs", label: L("المراجع", "References"), type: "json", help: L('["..."]', '["..."]') },
    { key: "published", label: L("منشور", "Published"), type: "boolean" },
  ],
  defaults: () => ({
    slug: "",
    title: emptyL,
    summary: emptyL,
    author: emptyL,
    author_role: emptyL,
    reading_time: 6,
    published_at: new Date().toISOString().slice(0, 10),
    image: "",
    sector_id: null,
    tags: [],
    sections: [],
    refs: [],
    published: true,
  }),
};

export const knowledgeResource: ResourceConfig = {
  table: "knowledge_articles",
  singular: L("مقال معرفي", "knowledge article"),
  orderBy: "sort_order",
  listColumns: [
    { key: "title", label: L("العنوان", "Title"), kind: "localized" },
    { key: "category", label: L("الفئة", "Category"), kind: "localized" },
    { key: "level", label: L("المستوى", "Level"), kind: "localized" },
    { key: "published", label: L("الحالة", "Status"), kind: "boolean" },
  ],
  fields: [
    { key: "slug", label: L("المعرّف (slug)", "Slug"), type: "text" },
    { key: "title", label: L("العنوان", "Title"), type: "localized" },
    { key: "summary", label: L("الملخص", "Summary"), type: "localizedLong" },
    { key: "category", label: L("الفئة", "Category"), type: "localized" },
    { key: "level", label: L("المستوى", "Level"), type: "localized" },
    { key: "icon", label: L("الأيقونة", "Icon"), type: "text" },
    { key: "reading_time", label: L("وقت القراءة (دقائق)", "Reading time (min)"), type: "number" },
    {
      key: "sections",
      label: L("أقسام الدرس", "Sections"),
      type: "json",
      help: L(
        '[{"heading":{"ar":"","en":""},"body":{"ar":"","en":""}}]',
        '[{"heading":{"ar":"","en":""},"body":{"ar":"","en":""}}]',
      ),
    },
    {
      key: "videos",
      label: L("الفيديوهات", "Videos"),
      type: "json",
      help: L(
        '[{"title":{"ar":"","en":""},"duration":"12:00","url":"https://youtube.com/watch?v=..."}]',
        '[{"title":{"ar":"","en":""},"duration":"12:00","url":"https://youtube.com/watch?v=..."}]',
      ),
    },
    { key: "sort_order", label: L("الترتيب", "Order"), type: "number" },
    { key: "published", label: L("منشور", "Published"), type: "boolean" },
  ],
  defaults: () => ({
    slug: "",
    title: emptyL,
    summary: emptyL,
    category: emptyL,
    level: emptyL,
    icon: "BookOpen",
    reading_time: 5,
    sections: [],
    videos: [],
    sort_order: 0,
    published: true,
  }),
};

export const boardResource: ResourceConfig = {
  table: "community_boards",
  singular: L("لوحة مجتمع", "community board"),
  orderBy: "sort_order",
  reorderable: true,
  listColumns: [
    { key: "name", label: L("الاسم", "Name"), kind: "localized" },
    { key: "slug", label: L("المعرّف", "Slug") },
    { key: "published", label: L("الحالة", "Status"), kind: "boolean" },
  ],
  fields: [
    { key: "slug", label: L("المعرّف (slug)", "Slug"), type: "text" },
    { key: "name", label: L("الاسم", "Name"), type: "localized" },
    { key: "description", label: L("الوصف", "Description"), type: "localizedLong" },
    { key: "image", label: L("صورة اللوحة", "Board image"), type: "image" },
    { key: "tone", label: L("اللون", "Tone"), type: "text" },
    { key: "sort_order", label: L("الترتيب", "Order"), type: "number" },
    { key: "published", label: L("منشورة", "Published"), type: "boolean" },
  ],
  defaults: () => ({
    slug: "",
    name: emptyL,
    description: emptyL,
    image: "",
    tone: "tone-emerald",
    sort_order: 0,
    published: true,
  }),
};

export const faqResource: ResourceConfig = {
  table: "faqs",
  singular: L("سؤال شائع", "FAQ"),
  orderBy: "sort_order",
  listColumns: [
    { key: "question", label: L("السؤال", "Question"), kind: "localized" },
    { key: "company_id", label: L("الشركة", "Company"), kind: "lookup", optionsKey: "companies" },
    { key: "published", label: L("الحالة", "Status"), kind: "boolean" },
  ],
  fields: [
    {
      key: "company_id",
      label: L("الشركة (اختياري)", "Company (optional)"),
      type: "select",
      optionsKey: "companies",
      help: L("اتركه فارغاً للأسئلة العامة.", "Leave empty for general FAQs."),
    },
    { key: "question", label: L("السؤال", "Question"), type: "localized" },
    { key: "answer", label: L("الإجابة", "Answer"), type: "localizedLong" },
    { key: "sort_order", label: L("الترتيب", "Order"), type: "number" },
    { key: "published", label: L("منشور", "Published"), type: "boolean" },
  ],
  defaults: () => ({
    company_id: null,
    question: emptyL,
    answer: emptyL,
    sort_order: 0,
    published: true,
  }),
};
