import {
  Activity,
  BarChart3,
  BookOpen,
  Brain,
  Building2,
  Calculator,
  Factory,
  FileText,
  Globe,
  Heart,
  Landmark,
  Laptop,
  PieChart,
  Rocket,
  Search,
  Shield,
  ShoppingBag,
  TrendingUp,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  zap: Zap,
  rocket: Rocket,
  shield: Shield,
  laptop: Laptop,
  brain: Brain,
  landmark: Landmark,
  factory: Factory,
  heart: Heart,
  shopping: ShoppingBag,
  building: Building2,
  chart: BarChart3,
  globe: Globe,
  search: Search,
  activity: Activity,
  calculator: Calculator,
  file: FileText,
  trending: TrendingUp,
  pie: PieChart,
  book: BookOpen,
};

export const getIcon = (key: string): LucideIcon => iconMap[key] ?? BarChart3;
