/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as CompaniesSlugRouteImport } from './routes/companies.$slug'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge.index'
import { Route as KnowledgeSlugRouteImport } from './routes/knowledge.$slug'
import { Route as ResearchIndexRouteImport } from './routes/research.index'
import { Route as ResearchSlugRouteImport } from './routes/research.$slug'
import { Route as SectorsIndexRouteImport } from './routes/sectors.index'
import { Route as SectorsSlugRouteImport } from './routes/sectors.$slug'
import { Route as AuthenticatedAdminCompaniesRouteImport } from './routes/_authenticated/admin.companies'
import { Route as AuthenticatedAdminResearchRouteImport } from './routes/_authenticated/admin.research'
import { Route as AuthenticatedAdminSectorsRouteImport } from './routes/_authenticated/admin.sectors'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesSlugRoute = CompaniesSlugRouteImport.update({
  id: '/companies/$slug',
  path: '/companies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeSlugRoute = KnowledgeSlugRouteImport.update({
  id: '/knowledge/$slug',
  path: '/knowledge/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIndexRoute = ResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchSlugRoute = ResearchSlugRouteImport.update({
  id: '/research/$slug',
  path: '/research/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsIndexRoute = SectorsIndexRouteImport.update({
  id: '/sectors/',
  path: '/sectors/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsSlugRoute = SectorsSlugRouteImport.update({
  id: '/sectors/$slug',
  path: '/sectors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminCompaniesRoute =
  AuthenticatedAdminCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResearchRoute =
  AuthenticatedAdminResearchRouteImport.update({
    id: '/research',
    path: '/research',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSectorsRoute =
  AuthenticatedAdminSectorsRouteImport.update({
    id: '/sectors',
    path: '/sectors',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/companies/$slug': typeof CompaniesSlugRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/sectors/$slug': typeof SectorsSlugRoute
  '/community/': typeof CommunityIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/sectors/': typeof SectorsIndexRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/research': typeof AuthenticatedAdminResearchRoute
  '/admin/sectors': typeof AuthenticatedAdminSectorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/companies/$slug': typeof CompaniesSlugRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/sectors/$slug': typeof SectorsSlugRoute
  '/community': typeof CommunityIndexRoute
  '/companies': typeof CompaniesIndexRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/research': typeof ResearchIndexRoute
  '/sectors': typeof SectorsIndexRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/research': typeof AuthenticatedAdminResearchRoute
  '/admin/sectors': typeof AuthenticatedAdminSectorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/companies/$slug': typeof CompaniesSlugRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/sectors/$slug': typeof SectorsSlugRoute
  '/community/': typeof CommunityIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/sectors/': typeof SectorsIndexRoute
  '/_authenticated/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/_authenticated/admin/research': typeof AuthenticatedAdminResearchRoute
  '/_authenticated/admin/sectors': typeof AuthenticatedAdminSectorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/companies/$slug'
    | '/knowledge/$slug'
    | '/research/$slug'
    | '/sectors/$slug'
    | '/community/'
    | '/companies/'
    | '/knowledge/'
    | '/research/'
    | '/sectors/'
    | '/admin/companies'
    | '/admin/research'
    | '/admin/sectors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/companies/$slug'
    | '/knowledge/$slug'
    | '/research/$slug'
    | '/sectors/$slug'
    | '/community'
    | '/companies'
    | '/knowledge'
    | '/research'
    | '/sectors'
    | '/admin/companies'
    | '/admin/research'
    | '/admin/sectors'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/companies/$slug'
    | '/knowledge/$slug'
    | '/research/$slug'
    | '/sectors/$slug'
    | '/community/'
    | '/companies/'
    | '/knowledge/'
    | '/research/'
    | '/sectors/'
    | '/_authenticated/admin/companies'
    | '/_authenticated/admin/research'
    | '/_authenticated/admin/sectors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CompaniesSlugRoute: typeof CompaniesSlugRoute
  KnowledgeSlugRoute: typeof KnowledgeSlugRoute
  ResearchSlugRoute: typeof ResearchSlugRoute
  SectorsSlugRoute: typeof SectorsSlugRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
  ResearchIndexRoute: typeof ResearchIndexRoute
  SectorsIndexRoute: typeof SectorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$slug': {
      id: '/companies/$slug'
      path: '/companies/$slug'
      fullPath: '/companies/$slug'
      preLoaderRoute: typeof CompaniesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/$slug': {
      id: '/knowledge/$slug'
      path: '/knowledge/$slug'
      fullPath: '/knowledge/$slug'
      preLoaderRoute: typeof KnowledgeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/': {
      id: '/research/'
      path: '/research'
      fullPath: '/research/'
      preLoaderRoute: typeof ResearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/$slug': {
      id: '/research/$slug'
      path: '/research/$slug'
      fullPath: '/research/$slug'
      preLoaderRoute: typeof ResearchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors/': {
      id: '/sectors/'
      path: '/sectors'
      fullPath: '/sectors/'
      preLoaderRoute: typeof SectorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors/$slug': {
      id: '/sectors/$slug'
      path: '/sectors/$slug'
      fullPath: '/sectors/$slug'
      preLoaderRoute: typeof SectorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/companies': {
      id: '/_authenticated/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/research': {
      id: '/_authenticated/admin/research'
      path: '/research'
      fullPath: '/admin/research'
      preLoaderRoute: typeof AuthenticatedAdminResearchRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sectors': {
      id: '/_authenticated/admin/sectors'
      path: '/sectors'
      fullPath: '/admin/sectors'
      preLoaderRoute: typeof AuthenticatedAdminSectorsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCompaniesRoute: typeof AuthenticatedAdminCompaniesRoute
  AuthenticatedAdminResearchRoute: typeof AuthenticatedAdminResearchRoute
  AuthenticatedAdminSectorsRoute: typeof AuthenticatedAdminSectorsRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCompaniesRoute: AuthenticatedAdminCompaniesRoute,
  AuthenticatedAdminResearchRoute: AuthenticatedAdminResearchRoute,
  AuthenticatedAdminSectorsRoute: AuthenticatedAdminSectorsRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CompaniesSlugRoute: CompaniesSlugRoute,
  KnowledgeSlugRoute: KnowledgeSlugRoute,
  ResearchSlugRoute: ResearchSlugRoute,
  SectorsSlugRoute: SectorsSlugRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
  ResearchIndexRoute: ResearchIndexRoute,
  SectorsIndexRoute: SectorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
