/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectorsIndexRouteImport } from './routes/sectors.index'
import { Route as SectorsSlugRouteImport } from './routes/sectors.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsIndexRoute = SectorsIndexRouteImport.update({
  id: '/sectors/',
  path: '/sectors/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsSlugRoute = SectorsSlugRouteImport.update({
  id: '/sectors/$slug',
  path: '/sectors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sectors/$slug': typeof SectorsSlugRoute
  '/sectors/': typeof SectorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sectors/$slug': typeof SectorsSlugRoute
  '/sectors': typeof SectorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sectors/$slug': typeof SectorsSlugRoute
  '/sectors/': typeof SectorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sectors/$slug' | '/sectors/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sectors/$slug' | '/sectors'
  id: '__root__' | '/' | '/sectors/$slug' | '/sectors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SectorsSlugRoute: typeof SectorsSlugRoute
  SectorsIndexRoute: typeof SectorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors/': {
      id: '/sectors/'
      path: '/sectors'
      fullPath: '/sectors/'
      preLoaderRoute: typeof SectorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors/$slug': {
      id: '/sectors/$slug'
      path: '/sectors/$slug'
      fullPath: '/sectors/$slug'
      preLoaderRoute: typeof SectorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SectorsSlugRoute: SectorsSlugRoute,
  SectorsIndexRoute: SectorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
